ktor:
    application:
        modules:
            - com.devx.ApplicationKt.module
    deployment:
        port: 5432
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
